# Generated by Django 4.0.4 on 2022-04-17 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('around', '0002_neighborhood'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='userProfile',
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
