# Generated by Django 4.0.4 on 2022-04-17 23:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('around', '0003_rename_user_userprofile_alter_neighborhood_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userProfile',
            new_name='Profile',
        ),
    ]
