# Generated by Django 4.0.4 on 2022-04-19 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('around', '0008_alter_business_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
    ]
